//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QFramework.Example
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    // Generate Id:22157f2a-92b9-4d9c-9e04-c847199632b7
    public partial class SetupPanel
    {
        
        public const string NAME = "SetupPanel";
        
        [SerializeField()]
        public UnityEngine.UI.Button BtnStart;
        
        [SerializeField()]
        public UnityEngine.UI.Button BtnSetting;
        
        [SerializeField()]
        public UnityEngine.UI.Button BtnExit;
        
        private SetupPanelData mPrivateData = null;
        
        public SetupPanelData Data
        {
            get
            {
                return mData;
            }
        }
        
        SetupPanelData mData
        {
            get
            {
                return mPrivateData ?? (mPrivateData = new SetupPanelData());
            }
            set
            {
                mUIData = value;
                mPrivateData = value;
            }
        }
        
        protected override void ClearUIComponents()
        {
            BtnStart = null;
            BtnSetting = null;
            BtnExit = null;
            mData = null;
        }
    }
}
