//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityEngine.EventSystems;
using UnityEngine.SceneManagement;

namespace QFramework.Example
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    public class SetupPanelData : QFramework.UIPanelData
    {
    }
    
    public partial class SetupPanel : QFramework.UIPanel
    {
        
        protected override void ProcessMsg(int eventId, QFramework.QMsg msg)
        {
            throw new System.NotImplementedException ();
        }
        
        protected override void OnInit(QFramework.IUIData uiData)
        {
            mData = uiData as SetupPanelData ?? new SetupPanelData();
            // please add init code here
            
            BtnStart.onClick.AddListener(() =>
            {
                SceneMgr.Load(1, () =>
                {

                    UIKit.CloseAllPanel();

                    
                });
            });
            
            BtnSetting.onClick.AddListener(() =>
            {
                UIKit.OpenPanel<SettingPanel>();
            });
            
            BtnExit.onClick.AddListener(() =>
            {
                Debug.Log("退出游戏");
                Application.Quit();
            });
        }
        
        protected override void OnOpen(QFramework.IUIData uiData)
        {
        }
        
        protected override void OnShow()
        {
        }
        
        protected override void OnHide()
        {
        }
        
        protected override void OnClose()
        {
            transform.Find("../../UICamera").gameObject.SetActive(false);
            transform.Find("../../EventSystem").gameObject.SetActive(false);
        }
    }
}
